#!/usr/bin/env node
/**
 * Syncs your Mux account's video library into the app.
 *
 *   npm run sync-mux
 *
 * Reads MUX_TOKEN_ID / MUX_TOKEN_SECRET from `.env.local` (gitignored), lists
 * every *ready* asset that has a **public** playback id, and writes
 * `src/data/mux-library.generated.ts`. The token never leaves this script —
 * the app only ever ships the public playback ids.
 *
 * Create a token at https://dashboard.mux.com/settings/access-tokens with
 * "Mux Video" → Read permission.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(root, 'src/data/mux-library.generated.ts');

function loadEnvLocal() {
  let raw;
  try {
    raw = readFileSync(join(root, '.env.local'), 'utf8');
  } catch {
    return;
  }
  for (const line of raw.split('\n')) {
    const m = line.match(/^\s*([\w.]+)\s*=\s*(.*)\s*$/);
    if (!m || line.trimStart().startsWith('#')) continue;
    const value = m[2].replace(/^["']|["']$/g, '');
    if (!(m[1] in process.env)) process.env[m[1]] = value;
  }
}

async function fetchAllAssets(auth) {
  const assets = [];
  for (let page = 1; ; page++) {
    const res = await fetch(`https://api.mux.com/video/v1/assets?limit=100&page=${page}`, {
      headers: { Authorization: `Basic ${auth}` },
    });
    if (!res.ok) {
      throw new Error(`Mux API ${res.status} ${res.statusText}: ${await res.text()}`);
    }
    const body = await res.json();
    const batch = body.data ?? [];
    assets.push(...batch);
    if (batch.length < 100) return assets;
  }
}

function render(entries) {
  const lines = entries.map(
    (e) =>
      `  { assetId: ${JSON.stringify(e.assetId)}, playbackId: ${JSON.stringify(
        e.playbackId,
      )}, passthrough: ${JSON.stringify(e.passthrough)}, durationSec: ${e.durationSec} },`,
  );
  return `/**
 * AUTO-GENERATED by \`npm run sync-mux\` — do not edit by hand.
 *
 * Mirrors your Mux account's assets (public playback only). The \`passthrough\`
 * field is what you set on each Mux upload; we use it to match a video to a
 * lesson id (e.g. passthrough "l1" → lesson "l1"). Until you run the sync this
 * is an empty list and lessons fall back to their placeholder.
 */

export type MuxLibraryEntry = {
  /** Mux asset id. */
  assetId: string;
  /** Public playback id — safe to ship. */
  playbackId: string;
  /** Mux \`passthrough\` value; we map it to a lesson id. */
  passthrough: string | null;
  /** Asset duration in seconds (rounded). */
  durationSec: number;
};

export const MUX_LIBRARY: MuxLibraryEntry[] = [
${lines.join('\n')}
];
`;
}

async function main() {
  loadEnvLocal();
  const id = process.env.MUX_TOKEN_ID;
  const secret = process.env.MUX_TOKEN_SECRET;
  if (!id || !secret) {
    console.error(
      'Missing MUX_TOKEN_ID / MUX_TOKEN_SECRET.\n' +
        'Add them to .env.local (see .env.example), then re-run `npm run sync-mux`.',
    );
    process.exit(1);
  }

  const auth = Buffer.from(`${id}:${secret}`).toString('base64');
  const assets = await fetchAllAssets(auth);

  const entries = [];
  const skipped = [];
  for (const a of assets) {
    const publicId = (a.playback_ids ?? []).find((p) => p.policy === 'public');
    if (a.status !== 'ready' || !publicId) {
      skipped.push({ id: a.id, status: a.status, public: Boolean(publicId) });
      continue;
    }
    entries.push({
      assetId: a.id,
      playbackId: publicId.id,
      passthrough: a.passthrough ?? null,
      durationSec: Math.round(a.duration ?? 0),
    });
  }

  writeFileSync(OUT, render(entries), 'utf8');

  console.log(`✓ Synced ${entries.length} asset(s) → src/data/mux-library.generated.ts`);
  for (const e of entries) {
    const map = e.passthrough ? `passthrough "${e.passthrough}"` : 'NO passthrough (won’t map to a lesson)';
    console.log(`  • ${e.playbackId}  ${e.durationSec}s  ${map}`);
  }
  if (skipped.length) {
    console.log(
      `\n${skipped.length} asset(s) skipped (not ready, or no public playback id):`,
    );
    for (const s of skipped) {
      console.log(`  • ${s.id}  status=${s.status}  public=${s.public}`);
    }
  }
  if (entries.some((e) => !e.passthrough)) {
    console.log(
      '\n⚠️  Some assets have no `passthrough`. Set each video\'s passthrough to a lesson id\n' +
        '   (l1, l2, l3…) in the Mux dashboard or at upload time so it maps to a lesson.',
    );
  }
}

main().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
