/**
 * AUTO-GENERATED by `npm run sync-mux` — do not edit by hand.
 *
 * Mirrors your Mux account's assets (public playback only). The `passthrough`
 * field is what you set on each Mux upload; we use it to match a video to a
 * lesson id (e.g. passthrough "l1" → lesson "l1"). Until you run the sync this
 * is an empty list and lessons fall back to their placeholder.
 */

export type MuxLibraryEntry = {
  /** Mux asset id. */
  assetId: string;
  /** Public playback id — safe to ship. */
  playbackId: string;
  /** Mux `passthrough` value; we map it to a lesson id. */
  passthrough: string | null;
  /** Asset duration in seconds (rounded). */
  durationSec: number;
};

export const MUX_LIBRARY: MuxLibraryEntry[] = [
  { assetId: "kG5Ts02zAiZL9jhzsqAZ02nG8mIO39lA8iOv00EljvgUN4", playbackId: "tq02FcCMn5gGMqAQJhn3cxF01YIXaczd8V02GCaNYGmykw", passthrough: null, durationSec: 5 },
];
